### PR TITLE
fix(mu): stop queue size metric from becoming negative

### LINKED ISSUE #918: bug(mu): negative queue size metrics
## Background
Currently, we send a metric to prometheus client Queue Size. In some MUs, this metric is received as a negative. Investigate and solve this issue.

## Developer Notes

This metric is a gauge. However, it should never go below zero. The issue probably originates in the queue recovery - the queue is initialized with tasks, but the gauge is not incremented. When they a decremented, we go negative.

[Original Implementation](https://github.com/permaweb/ao/issues/830)

### PR DESCRIPTION
**Pull request by jfrain99**
Closes #918 

Fixes the implementation of the worker queue size metric implementation in the MU. Now, returns the max queue size in the last minute.

### CODE REVIEW

File: servers/mu/src/domain/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ import { createLogger } from './logger.js'
 import { cuFetchWithCache } from './lib/cu-fetch-with-cache.js'
 import { handleWorkerQueueMessage } from './lib/handle-worker-queue-message.js'
 import { BroadcastChannel } from 'node:worker_threads'
-
+import { apply } from 'ramda'
```
Comment (TillaTheHun0) [inline servers/mu/src/domain/index.js:30]: Could we fix the order of these import statements? `node` imports at the top, then imports from `node_modules`, then locals

File: servers/mu/src/domain/index.js [hunk 2]
```diff
@@ -44,9 +44,13 @@ const histogram = MetricsClient.histogramWith()({
...
   labelNames: ['method', 'operation', 'errorType', 'status', 'statusGroup']
 })
+const maximumQueueArray = new Array(60).fill(undefined)
+const maximumQueueTimeArray = new Array(60).fill(undefined)
+
 const workerQueueGauge = MetricsClient.gaugeWith({})({
   name: 'queue_size',
-  description: 'The size of the queue'
+  description: 'The size of the queue',
+  collect: () => apply(Math.max, maximumQueueArray)
```
Comment (TillaTheHun0) [inline servers/mu/src/domain/index.js:53]: much cleaner 👍

File: servers/mu/src/domain/lib/handle-worker-queue-message.js [hunk 3]
```diff
@@ -1,16 +1,37 @@
-function metricsMessageHandler (payload, gauge) {
-  if (payload.action === 'enqueue') {
-    gauge.inc()
-  }
-  if (payload.action === 'dequeue') {
-    gauge.dec()
+function metricsMessageHandler (payload, maximumQueueArray, maximumQueueTimeArray) {
+  const { size, time } = payload
+  const seconds = Math.floor(time / 1000 % 60)
```
Comment (TillaTheHun0) [inline servers/mu/src/domain/lib/handle-worker-queue-message.js:3]: Hopefully this doesn't slow things down to much. Should be fine.

**Review by TillaTheHun0 — APPROVED** [review]
LGTM
